# Generated by Django 5.1.1 on 2024-10-05 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user_id', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=128)),
                ('success', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAttributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('full_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='User Full Name')),
                ('given_name', models.CharField(blank=True, max_length=35, null=True, verbose_name='Given Name')),
                ('family_name', models.CharField(blank=True, max_length=35, null=True, verbose_name='Family Name')),
                ('user_metadata', models.JSONField(default=dict, null=True, verbose_name='User data')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
