name: Build and publish Letter C
on:
  push:
    branches:
      - main
    paths:
      - 'c/src/**'
      - 'c/.env'
      - 'c/healthcheck.js'
      - 'c/next.config.mjs'
      - 'c/package.json'
      - 'c/package-lock.json'
      - 'c/Dockerfile'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./c
          file: c/Dockerfile
          tags: |
            ${{ github.repository }}-letter-c:latest
            ${{ github.repository }}-letter-c:${{ github.sha }}
