name: Build and publish Letter A
on:
  push:
    branches:
      - main
    paths:
      - 'a/scripts/**'
      - 'a/src/**'
      - 'a/Dockerfile'
      - 'a/LetterA.sln'
      - 'a/Directory.Build.props'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./a
          file: a/Dockerfile
          tags: |
            ${{ github.repository }}-letter-a:latest
            ${{ github.repository }}-letter-a:${{ github.sha }}
